GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Abbey Did",
    "email": "abbey@did.com",
    "password": "Abcdefgh1",
    "password2": "Abcdefgh1"
}

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "shannon@gmail.com",
    "password": "test"
}

###

GET http://localhost:5000/api/posts
Authorization: jwtToken

###

POST http://localhost:5000/api/token
Content-Type: application/json

{
    "token": "jwtRefresh"
}

###

POST http://localhost:5000/api/logout
Content-Type: application/json
Authorization: jwtToken

{
    "token": "jwtRefresh"
}